### PR TITLE
feat: History Parser

### PR DESCRIPTION
**Pull request by TsukimiRini**
#127
image

### CODE REVIEW

**Comment by TsukimiRini** [comment]
History parser只用于将一个repo的所有历史版本都各自转为uritree并存储在cache中。
载入cache时需要调用`CacheHandler`的`loadCache`函数：
```java
Pair<URITree, URI> loadCache(String cacheDir, URITree tree);
```

**Comment by shigma** [comment]
Only occurs on first run:

image

**Comment by shigma** [comment]
Mysterious empty `modifiedFilePath`:

image

image

**Comment by TsukimiRini** [comment]
> Mysterious empty `modifiedFilePath`

fixed by [bf11b07](https://github.com/Symbolk/Code2Graph/pull/129/commits/bf11b0760eaee7f970691f4fea271effae1deafa)

**Comment by TsukimiRini** [comment]
> Only occurs on first run:
> 
> image

fixed by [3f74f74](https://github.com/Symbolk/Code2Graph/pull/129/commits/3f74f7425c06f7c38d0ec08e20309f20a2df79f6)

**Review by shigma — APPROVED** [review]

**Pull request merged**
